import './globals.css'
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import HeaderNavigation from "@/app/components/HeaderNavigation";
import AIAsistant from "@/app/components/AIAsistant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yeah Elections",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicons/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

        <link rel="prefetch" href="/quizzles" as="document" />
        <link rel="prefetch" href="/achievements" as="document" />
        <link rel="prefetch" href="/map" as="document" />
      </head>

      <body className={inter.className}>
        <Providers>
          <HeaderNavigation />
          {/* <div className="fixed z-0 top-1/2 center place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[260px]"></div> */}

          <div className="light max-w-[1024px] grid px-6 pb-10">{children}</div>

          <AIAsistant />
        </Providers>
      </body>
    </html>
  );
}
